name: Linting and style checking

on: [push, pull_request]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Lint
        run: luacheck lua/

  stylua:
    name: stylua
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color never --check lua/
